### ISSUE TITLE
ColorBarWidget slow initialization

### ISSUE THREAD

**Issue by ZacDiggum** [vispy/vispy#1398]
Hi,
I have a tiny piece of code implementing a 3D view and a separate ColorBarWidget both arranged in a grid:
```
canvas = SceneCanvas(keys='interactive')
grid = canvas.central_widget.add_grid()
view = grid.add_view(col_span=9)
colorbar = ColorBarWidget(my_settings_go_here)
colorbar = grid.add_widget(colorbar)
```
Of course there are other objects to be rendered inside `view` but only adding `colorbar` to `grid`  leads to significant longer execution times of the script, like an extra 5 seconds. Now I wonder why ColorBarWidget makes everything so slow.
I'm using PyQt5 and the latest vispy from the github repo. The performance issue occurs both under Windows (10) and Linux (Mint).
Anything I could do about that?

**Comment by larsoner** [comment]
Can you see if adding a `TextVisual` object with ~20 characters instead of a colorbar also takes a while? That will tell us whether it's the SDF rendering (most likely) or something specific about the colorbar visual (possible but less likely).

**Comment by ZacDiggum** [comment]
Hm, `Text()` works fine even for strings with length 100.
I think I found the problem. I use a custom colormap with 240 colors: a DIY version of 'jet' colormap from blue (hue 240) to red (hue 0). Decreasing the number of colors greatly decreases the time until the window is displayed. On the other hand, the size of the colormap didn't affect rendering large `GridMesh()` and `Markers()` objects, just the `ColorBarWidget()`.

**Comment by larsoner** [comment]
This would probably be fixed by #1052

**Comment by ZacDiggum** [comment]
Ah, I see. Okay, then I'll close this issue. Thank you...

**Comment by rsinghoyla** [comment]
@larsoner I know this issue was closed. And #1052 seems to suggest that colorbar initialization delay would be solved in 0.6 I am using 0.6 but I still see an appreciable delay when I use
```scene.ColorBarWidget(label="", 
                                                        cmap='grays', orientation="left", border_width=1,
                                                        border_color = "#212121",label_color="white")```

**Comment by djhoese** [comment]
@rsinghoyla How many "visuals" do you have on your plot otherwise? Can you provide me with a minimal example that I can run and hopefully see this slow performance?

**Comment by rsinghoyla** [comment]
Thanks for your reply.

Here is a code — its initialising 6 view boxes and then adding colorbar and plotting an image (from laptop camera in models.py) in them.



If you uncomment lines 303-314 in vispy_pyqtsignal* and comment line 315, colorbars will be visualised but there is a starting delay.

BTW in my work I have to work with variable number of images, views. Sometimes I might display 2 images on the canvas, sometimes 4 etc… I have initialised a max number of view boxes and I add and remove view boxes from grid (and set image data to none — see update_canvas function) every few frames.. is this the right approach? 
(For above problem, colorbar delay I have commented out update_canvas)

Thanks

**Comment by kmuehlbauer** [comment]
@rsinghoyla Somehow, the attachment code wasn't feed trough. Maybe because of sending by EMail?

**Comment by rsinghoyla** [comment]
[vispy_pyqtsignal_live_camera2.py.txt](https://github.com/vispy/vispy/files/3402471/vispy_pyqtsignal_live_camera2.py.txt)
[models.py.txt](https://github.com/vispy/vispy/files/3402473/models.py.txt)

**Comment by rsinghoyla** [comment]
I hope that helps.

**Comment by djhoese** [comment]
@rsinghoyla Are you using PyQt5 or PyQt4? It looks like your script tries to import PyQt4 first. Is performance with vispy 0.6 better, worse, or about the same for PyQt4 versus PyQt5?

**Comment by rsinghoyla** [comment]
I have pyqt5 only on my system.. so I have no comparison with pyqt4. we were working with vispy 0.5+ till recently; I dont see an improvement in speed, the matplotlib colormaps have helped though.

**Comment by kmuehlbauer** [comment]
@rsinghoyla Thanks for the code, but I did not manage to comprehend where the exact problem is. Can you create a minimal reproducible example showing the Colorbar problems.
