### ISSUE TITLE
Adding colorbar shrinks plot

### ISSUE THREAD

**Issue by moflaher** [vispy/vispy#1644]
When adding a colorbar to a figure it drastically reduces the size of the plot. I'm using vispy version 0.5.3.

Here is the code to generate the plot with and without a colorbar.

`import numpy as np
import vispy
from vispy.plot import Fig
import matplotlib as mpl

x,y=np.meshgrid(np.arange(5,15,1),np.arange(10,30,1))
tri=mpl.tri.Triangulation(x.flatten(),y.flatten())

def exp_z_inv(x, y):
    z = np.complex(x, y)
    f = np.exp(1.0 / z)
    return np.angle(f, deg=True)    
v_fn = np.vectorize(exp_z_inv)
z=v_fn(tri.x,tri.y)

fig = Fig(bgcolor='w')
ax = fig[0, 0]
mesh=vispy.geometry.MeshData(np.vstack([tri.x,tri.y,z*0]).T,tri.triangles,vertex_values=z)
m=ax.mesh(meshdata=mesh,shading='flat')
m.cmap=vispy.color.colormap.get_colormap('viridis')
fig.app.run()

fig = Fig(bgcolor='w')
ax = fig[0, 0]
mesh=vispy.geometry.MeshData(np.vstack([tri.x,tri.y,z*0]).T,tri.triangles,vertex_values=z)
m=ax.mesh(meshdata=mesh,shading='flat')
m.cmap=vispy.color.colormap.get_colormap('viridis')
ax.colorbar('viridis',clim=(z.min(),z.max()),position='right')
fig.app.run()
`

**Comment by djhoese** [comment]
This looks like it is an issue with `.mesh`. If I change your code to use an image:

```python
fig = Fig(bgcolor='w')
ax = fig[0, 0]
img = ax.image(np.random.random((100, 100)))
img.cmap = vispy.color.colormap.get_colormap('viridis')
ax.colorbar('viridis', clim=(z.min(), z.max()), position='right')
fig.app.run()
```

I get:

![image](https://user-images.githubusercontent.com/1828519/58567818-b16b9100-81f8-11e9-8545-dd232b152fcb.png)

**Comment by djhoese** [comment]
I think I've figured it out and bottom line is that handling a colorbar doesn't look like it was ever implemented for 3D views. Compare the `_configure_3d` method linked below to the `_configure_2d` method defined above it.

https://github.com/vispy/vispy/blob/master/vispy/plot/plotwidget.py#L154

**Comment by queenish001** [comment]
@moflaher Is your issue resolved now? :)

**Comment by djhoese** [comment]
I think this is still an issue and will take some time investment to figure out.
